# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Build CI

on:
  push:
    branches: [master, fix-*, feat-*]
    tags: [v*]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y libgtkmm-3.0-dev libcurl4-gnutls-dev libyajl-dev valgrind
    - uses: actions/checkout@v4
    - run: ./build/launch.sh
    - run: which samrewritten
    - run: cd package && ./build_appimage.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SamRewritten
        path: package/Sam*.AppImage 
